name: Deploy docs to GH pages

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv export --only-group docs --no-emit-workspace --no-dev --no-header --no-hashes --output-file requirements.txt && pip install -r requirements.txt
      - name: Sphinx build
        run: |
          cp -r ./analytics/notebooks ./docs/notebooks
          cp -r ./analytics/images ./docs/images
          sphinx-build docs _build
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/

  # Deployment job
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4